Protect against SBOM and VEX file overwriting
Writing directly to to ${DEPLOY_DIR} is problematic, and using sstate to
manage it overcomes these problems. If multiple recipes writes to the same
sbom/vex files, bitbake will happily overwrite the existing content,
without any errors or warnings. The last write wins.

While commit 5c8b10d49f7c ("breaking: add support for multiple targets (#10)")
fixed this so that this does not happens when building multiple recipes,
the problem still persists when building multiple machines, as ${MACHINE}
is not included in the deploy paths.

The problem could also occur when using custom CYCLONEDX_EXPORT_DIR and/or
CYCLONEDX_EXPORT_SBOM and CYCLONEDX_EXPORT_VEX, causing such file
conflicts.

By using the sstate mechanism to write to ${DEPLOY_DIR}, if/when such
problems occurs bitbake will error out instead of silently overwriting.

The use of do_deploy_cyclonedx[cleandirs] before this commit also did not
really work, as cleandirs flags is only processed for actual tasks, which
do_deploy_cyclonedx was not prior to this commit.

If you get errors like this when building:

ERROR: os-rootfs-1.0-r0 do_deploy_cyclonedx: Recipe os-rootfs is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  /home/user/scarthgap/build/tmp-glibc/deploy/cyclonedx-export/bom.json
    (matched in manifest-machine-imx-boot.deploy_cyclonedx)
  /home/user/scarthgap/build/tmp-glibc/deploy/cyclonedx-export/vex.json
    (matched in manifest-machine-imx-boot.deploy_cyclonedx)
Please adjust the recipes so only one recipe provides a given file.

it means you are trying to deploy multiple files to the same path, and you
need to redefine CYCLONEDX_EXPORT_DIR and/or CYCLONEDX_EXPORT_SBOM
and CYCLONEDX_EXPORT_VEX, so that you deploy to different paths for all the
different SBOM and VEX files you have.