Fix cleaning of leftovers when previous builds
The cleandirs flag is only valid for bitbake tasks, and does nothing for
handler functions.

So we need to do the cleanup manually in the handler function instead.

In addition to the problems described in the comment before the function,
switching between different MACHINE configurations in the same build dir
was causing problems, such as this:

ERROR: mc:initramfs:perl-5.38.2-r0 do_populate_cyclonedx_setscene: Recipe perl is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  /build/tmp-musl/cyclonedx/perl/pn-list.json
    (matched in manifest-cortexa53-crypto-perl.populate_cyclonedx)
Please adjust the recipes so only one recipe provides a given file.
WARNING: Logfile for failed setscene task is /build/tmp-musl/work/core2-64-oe-linux-musl/perl/5.38.2/temp/log.do_populate_cyclonedx_setscene.1512710
WARNING: Setscene task (mc:initramfs:/src/oe-core/meta/recipes-devtools/perl/perl_5.38.2.bb:do_populate_cyclonedx_setscene) failed with exit code '1' - real task will be run instead

Fixes: d3a78c04785e ("Limit SBOM content to packages added to the rootfs")
Signed-off-by: Esben Haabendal <esben@geanix.com>